[tool.poetry]
name = "studio-custom-names"
version = "0.1.0"
description = ""
authors = ["GSG-Robots"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
elevate = "^0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
